version : 2

sources:
  - name: raw
    schema: gz_raw_data
    database: fourth-buffer-484809-j2
    loader: bigquery
    tables: 
      - name: product
        identifier: raw_gz_product
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship