version : 2

sources:
  - name: raw
    schema: gz_raw_data
    database: fourth-buffer-484809-j2
    loader: bigquery
    tables: 
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have the price for each product
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
          
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have the orders, the products, the revenue and the quantity per date
        tests:
          - unique: 
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweez / we have shipping fee, logcost and ship_cost per orders id
        columns:
        - name: orders_id
          tests:
            - unique
            - not_null
      
      - name: adwords
        identifier: raw_gz_adwords
        description: ads cost, impression and click for each campaign key
        tests:
          - unique: 
              column_name: "(date || '-' || campaign_key)"
      
      - name: bing
        identifier: raw_gz_bing
        description: bing campaign
        tests:
          - unique: 
              column_name: "(date || '-' || campgn_key)"

      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaign
        tests:
          - unique: 
              column_name: "(date || '-' || campgn_key)"

      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaign
        tests:
          - unique: 
              column_name: "(date || '-' || campgn_key)"
       
models: 
  - name: int_campaigns_day
    columns:
      - name: click
        tests:
          - not_null
      - name: impressions
        tests:
          - not_null
      - name: ads_cost
        tests:
          - not_null